name: Build RootFS

on:
  push:
    branches:
      - "stable"
      - "unstable"
      - "testing"
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          chmod +x gh-build.sh
          mkdir ouputs
          sudo ./gh-build.sh amd64
          sudo ./gh-build.sh arm64

      - name: Store AMD64
        uses: actions/upload-artifact@v3
        with:
          name: rootfs_amd64
          path: ouputs/rootfs_amd64_${{GITHUB_REF_NAME}}.tar.xz

      - name: Store ARM64
        uses: actions/upload-artifact@v3
        with:
          name: rootfs_arm64
          path: ouputs/rootfs_arm64_${{GITHUB_REF_NAME}}.tar.xz
